import MarketingFooter from "@/components/MarketingFooter";

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <div className="rw-shell legal-container">
        <h1 className="legal-title">Privacy Policy</h1>
        <p className="legal-updated">Last updated: March 2026</p>

        <section className="legal-section">
          <h2>Overview</h2>
          <p>
            RevenueWatch provides read-only monitoring and alerting for connected
            Stripe accounts. This Privacy Policy explains what information we
            collect, how we use it, and how we protect it.
          </p>
        </section>

        <section className="legal-section">
          <h2>Information we collect</h2>
          <p>We may collect and store the following information:</p>
          <ul>
            <li>Account and business contact information you provide to us.</li>
            <li>Connected Stripe account identifiers and related metadata.</li>
            <li>Alert data generated by our monitoring system.</li>
            <li>Technical logs needed for reliability, debugging, and security.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>How we use information</h2>
          <ul>
            <li>To operate RevenueWatch and provide monitoring and alerting services.</li>
            <li>To send alert emails and service-related communications.</li>
            <li>To maintain reliability, security, and system performance.</li>
            <li>To investigate issues, prevent abuse, and comply with legal obligations.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>Stripe data access</h2>
          <p>
            RevenueWatch is designed as a read-only monitoring tool. We do not
            move money, modify billing settings, or process customer payments on
            your behalf.
          </p>
          <p>
            Data accessed from Stripe is used solely for monitoring purposes and
            is not shared with third parties beyond operational service providers
            needed to run RevenueWatch.
          </p>
        </section>

        <section className="legal-section">
          <h2>Data retention</h2>
          <p>
            We retain data only as long as reasonably necessary to provide the
            service, maintain operational records, improve reliability, and
            comply with legal obligations.
          </p>
        </section>

        <section className="legal-section">
          <h2>Data sharing</h2>
          <p>
            We do not sell your data. We may share data only with service
            providers necessary to operate RevenueWatch, such as hosting, email
            delivery, database, and infrastructure providers, or when required by
            law.
          </p>
        </section>

        <section className="legal-section">
          <h2>Security</h2>
          <p>
            We take reasonable technical and organizational measures to protect
            data against unauthorized access, misuse, or disclosure. However, no
            system can be guaranteed to be completely secure.
          </p>
        </section>

        <section className="legal-section">
          <h2>Your choices</h2>
          <p>
            You may contact us to request account disconnection or ask questions
            about your data. Disconnecting a Stripe account pauses monitoring for
            that account.
          </p>
        </section>

        <section className="legal-section">
          <h2>GDPR and data rights</h2>
          <p>
            We comply with applicable data protection laws, including the General
            Data Protection Regulation (GDPR). Users in the European Union may
            request access to, correction of, or deletion of their personal data
            by contacting us.
          </p>
        </section>

        <section className="legal-section">
          <h2>Contact</h2>
          <p>
            For privacy questions, contact us at{" "}
            <a href="mailto:contact@revenuewatch.app">contact@revenuewatch.app</a>.
          </p>
        </section>
      </div>

      <MarketingFooter />
    </main>
  );
}
