const EURO = "\u20AC";
const RIGHT_ARROW = "\u2192";

export const subscriptionHealthPreview = {
  overview: {
    activeSubscriptions: 428,
    estimatedMrr: `${EURO}18,420`,
    needsReview: 3,
    failedRenewals: 14,
    trialing: 32,
    pastDue: 9,
    unpaid: 4,
    canceled: "5 this week",
    netMovement: "+18 this month",
  },
  accounts: [
    {
      stripeAccountId: "preview-northstar",
      name: "Northstar Commerce",
      status: "Review needed",
      activeSubscriptions: 124,
      estimatedMrr: `${EURO}6,420`,
      activeAlerts: 1,
      lastActivity: "12m ago",
    },
    {
      stripeAccountId: "preview-bluepeak",
      name: "BluePeak Studio",
      status: "Monitoring active",
      activeSubscriptions: 88,
      estimatedMrr: `${EURO}3,900`,
      activeAlerts: 1,
      lastActivity: "45m ago",
    },
    {
      stripeAccountId: "preview-cedar",
      name: "Cedar Labs",
      status: "Attention needed",
      activeSubscriptions: 216,
      estimatedMrr: `${EURO}8,100`,
      activeAlerts: 1,
      lastActivity: "2h ago",
    },
  ],
  inboxSummary: {
    needsReview: 3,
    failedRenewals: 14,
    attentionNeeded: 1,
    reviewedRecently: 3,
  },
  issues: [
    {
      id: "preview-subscription-canceled",
      accountName: "Northstar Commerce",
      type: "subscription_canceled",
      typeLabel: "Subscription canceled",
      message:
        "A subscription was canceled. Parveil is monitoring the revenue impact and showing account context for review.",
      severityKind: "warning" as const,
      severityLabel: "Normal",
      severityTextColor: "#475569",
      severityBgColor: "#F8FAFC",
      typeColor: "#475569",
      detectedLabel: "12m ago",
      href: "/dashboard/accounts",
      createdAt: new Date("2026-06-01T11:18:00.000Z").toISOString(),
      context: JSON.stringify({
        estimatedMonthlyRevenue: 3900,
        currency: "EUR",
        status: "Canceled",
        planName: "Starter",
        detectedAt: "Today, 11:18 UTC",
      }),
    },
    {
      id: "preview-failed-renewal",
      accountName: "BluePeak Studio",
      type: "failed_renewal",
      typeLabel: "Failed renewal",
      message:
        "A subscription renewal payment failed. The subscription is now past due and the monthly amount is at risk. Parveil is monitoring the issue and showing account context for review.",
      severityKind: "warning" as const,
      severityLabel: "Review needed",
      severityTextColor: "#9a6700",
      severityBgColor: "#FFF7E6",
      typeColor: "#9a6700",
      detectedLabel: "45m ago",
      href: "/dashboard/accounts",
      createdAt: new Date("2026-06-01T14:32:00.000Z").toISOString(),
      context: JSON.stringify({
        amountDue: 3900,
        currency: "EUR",
        status: "Past due",
        planName: "Growth",
        recentActivity: [
          { label: "Payment attempt failed", time: "Today, 14:32 UTC" },
          { label: "Invoice created", time: "Today, 14:30 UTC" },
        ],
      }),
    },
    {
      id: "preview-subscription-drop",
      accountName: "Cedar Labs",
      type: "subscription_drop",
      typeLabel: "Subscription drop detected",
      message:
        "Active subscriptions dropped from 10 to 7. Parveil is showing the subscription movement so the account can be reviewed.",
      severityKind: "critical" as const,
      severityLabel: "Attention needed",
      severityTextColor: "#B42318",
      severityBgColor: "#FEF3F2",
      typeColor: "#B42318",
      detectedLabel: "2h ago",
      href: "/dashboard/accounts",
      createdAt: new Date("2026-06-01T13:05:00.000Z").toISOString(),
      context: JSON.stringify({
        previousActiveSubscriptions: 10,
        currentActiveSubscriptions: 7,
        dropPercent: -30,
        detectedAt: "Today, 13:05 UTC",
      }),
    },
  ],
  history: [
    {
      id: "preview-history-past-due",
      type: "past_due_increase",
      accountName: "BluePeak Studio",
      summary: "Past-due subscriptions increased from 0 to 2.",
      status: "Reviewed",
      time: "Yesterday, 16:20",
    },
    {
      id: "preview-history-unpaid",
      type: "unpaid_subscription",
      accountName: "Cedar Labs",
      summary: "2 subscriptions were marked unpaid.",
      status: "Reviewed",
      time: "Yesterday, 09:45",
    },
    {
      id: "preview-history-canceled",
      type: "subscription_canceled",
      accountName: "Northstar Commerce",
      summary: `A customer canceled a subscription. Estimated monthly revenue impact: ${EURO}39.`,
      status: "Reviewed",
      time: "May 21, 4:34 PM",
    },
  ],
  currentIssuesSummary: [
    "Subscription canceled",
    "Failed renewal",
    "Subscription drop detected",
  ],
};

export { EURO, RIGHT_ARROW };
